
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/var/lib/snapd/snap/clion/250/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Linux - 6.5.5-200.fc38.x86_64 - x86_64
...
